export const songs = [
  {
    id: 1,
    name: '25',
    author: 'Táo',
    path: '/music/song1.mp3',
    image: '/images/song1.jpg',
    category: 'rap',
  },
  {
    id: 2,
    name: 'OK',
    author: 'Binz',
    path: '/music/song2.mp3',
    image: '/images/song2.jpg',
    category: 'rap',
  },
  {
    id: 3,
    name: 'Về Bên Anh',
    author: 'Jack(G5R)',
    path: '/music/song3.mp3',
    image: '/images/song3.jpg',
    category: 'young',
  },
  {
    id: 4,
    name: 'Em đừng đi',
    author: 'Sơn Tùng MTP',
    path: '/music/song4.mp3',
    image: '/images/song4.jpg',
    category: 'young',
  },
  {
    id: 5,
    name: 'Anh Biết',
    author: 'Xám, D.Blue',
    path: '/music/song5.mp3',
    image: '/images/song5.jpg',
    category: 'rap',
  },
  {
    id: 6,
    name: 'Em Có Thể',
    author: 'Osad, VRT',
    path: '/music/song6.mp3',
    image: '/images/song6.jpg',
    category: 'rap',
  },
  {
    id: 7,
    name: 'Nắng Ấm Xa Dần',
    author: 'Sơn Tùng MTP',
    path: '/music/song7.mp3',
    image: '/images/song7.jpg',
    category: 'young',
  },
  {
    id: 8,
    name: 'Phía Sau Em',
    author: 'Kay Tran, Binz',
    path: '/music/song8.mp3',
    image: '/images/song8.jpg',
    category: 'rap',
  },
  {
    id: 9,
    name: 'SOFAR',
    author: 'Binz',
    path: '/music/song9.mp3',
    image: '/images/song9.jpg',
    category: 'rap',
  },
  {
    id: 10,
    name: 'Mãi Mãi Bên Nhau',
    author: 'Noo Phước Thịnh',
    path: '/music/song10.mp3',
    image: '/images/song10.jpg',
    category: 'young',
  },
  {
    id: 11,
    name: 'Mashup 30 Songs 2018',
    author: 'Rum ft Quang Hùng',
    path: '/music/song11.mp3',
    image: '/images/song11.jpg',
    category: 'young',
  },
  {
    id: 12,
    name: 'Con Đường Tôi',
    author: 'Trọng Hiếu',
    path: '/music/song12.mp3',
    image: '/images/song12.jpg',
    category: 'young',
  },
  {
    id: 13,
    name: 'Anh Thương Em Nhất Mà',
    author: 'Lã Long,TiB',
    path: '/music/song13.mp3',
    image: '/images/song13.jpg',
    category: 'young',
  },
  {
    id: 14,
    name: 'Chỉ Còn Ta Và Ta Giữa Trời',
    author: 'Killic,D.Blue',
    path: '/music/song14.mp3',
    image: '/images/song14.jpg',
    category: 'rap',
  },
  {
    id: 15,
    name: 'Có Lẽ Quá Khó Để Quên Một Người',
    author: '1nG,Namlee,D.Blue',
    path: '/music/song15.mp3',
    image: '/images/song15.jpg',
    category: 'young',
  },
  {
    id: 16,
    name: 'Lạnh Thôi Đừng Mưa',
    author: 'Hải Sâm',
    path: '/music/song16.mp3',
    image: '/images/song16.jpg',
    category: 'young',
  },
]